apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vibspecdb.fullname" . }}-app-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: vibspec-app-ip-address
    networking.gke.io/managed-certificates: vibspec-app-dev-certificate
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: {{ include "vibspecdb.fullname" . }}
      port:
        number: {{ .Values.service.port }}